### ISSUE TITLE
pkgu cann't be used on windows platform

### ISSUE THREAD

**Issue by Abeautifulsnow** [Abeautifulsnow/pkgu#10]
**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
```text
Traceback (most recent call last):
  File "C:\personal_folder\software\Python\Python311\Lib\site-packages\simple_term_menu.py", line 37, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\personal_folder\software\Python\Python311\Scripts\pkgu.exe\__main__.py", line 4, in <module>
  File "C:\personal_folder\software\Python\Python311\Lib\site-packages\pkgu.py", line 26, in <module>
    from simple_term_menu import TerminalMenu
  File "C:\personal_folder\software\Python\Python311\Lib\site-packages\simple_term_menu.py", line 39, in <module>
    raise NotImplementedError('"{}" is currently not supported.'.format(platform.system())) from e
NotImplementedError: "Windows" is currently not supported.
```

**Comment by Abeautifulsnow** [comment]
[python-inquirer](https://github.com/magmax/python-inquirer) supports windows platform.
